### ISSUE TITLE
Can you add barometer record?

### ISSUE THREAD

**Issue by QMonteCarlo** [waiwnf/pilotguru#35]
Hi, waiwnf,we have talked about the quality of GPS altitude, generally it's quite unreliable. A way to work around is to use the barometer as height indicator, 1 Hz output frequency is good enough. How would you like to consider adding this to the next version?

**Comment by waiwnf** [comment]
Hello. Sure, I should be able to get to it in a day or two.

**Comment by waiwnf** [comment]
692d21f69b4d1d1500a9f0a323d3df7acc76c51f

**Comment by waiwnf** [comment]
I think this works, but will only have time to check more thoroughly and push to play store tomorrow evening.

**Comment by waiwnf** [comment]
b606cd21262d8336037d880dbff11d3fe31dab61

**Comment by waiwnf** [comment]
2a7c75d3c981579b6ca86b0c70ea138d3d8ef160

New version just got pushed to play store, so closing this one. Pressure logging is off by default, you'll have to set the checkbox in preferences for it to become active. Let me know if there are any issues.
