### ISSUE TITLE
Magnetometer reading problem

### ISSUE THREAD

**Issue by LittleByLittle2** [waiwnf/pilotguru#39]
Hi Wananf,

I want to read magnetometer data from current program, how can I get the data?

Thank you.

Best,
Yu

**Comment by waiwnf** [comment]
Hi Yu. The app does not log the magnetometer data for now. I guess I can add an option to log that too, but that would have to wait for a few days for when I have time.

**Comment by LittleByLittle2** [comment]
Thank you. Hope to see the new version soon.
