### ISSUE TITLE
What about implementing your ideas in real hardware

### ISSUE THREAD

**Issue by adbor** [waiwnf/pilotguru#44]
Здравствуйте

Почитал ваши статьи, но не смог найти контакты (точнее нашел через habr личные сообшения - но там тишина). Решил попробовать связаться через "Issues". Как программист, могу понять несовсем этичность данного поступка, однако ваша статья и код заинтересовали, поэтому решил попробовать. В любом случае, уберу данное issue в конце недели

***********************************************************************************************************************
Меня зовут Алексей, я руководитель группы автопилота в компании ИТЭЛМА СП  ( https://www.itelma.ru/ )

Вот вакансии доступные у нас. 

1) Ведущий инженер-программист разработчик Автопилота
https://hh.ru/vacancy/68597689

2) Инженер-программист разработчик Автопилота
https://hh.ru/vacancy/68792010

Дайте пожалуйста обратную связи, если вам интересно [] (Telegram, Whatsapp, sms)
***********************************************************************************************************************

Алексей

**Comment by waiwnf** [comment]
This was pretty real: https://www.youtube.com/watch?v=G3CsO1vYlxI ;)

Спасибо за контакт! Ответил на хабре, отсюда отредактировал ваш телефон на всякий случай, чтобы личные данные лишнего не расползались.
